id: I8D89959A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:23:04+00:00'
last_modified: '2022-06-08T13:49:36.551560+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD152297
  title: 'ཡུལ་མདོ་ཁམས་སྟོད་ཀྱི་མཁས་གྲུབ་རྣམ་པའི་གསུང་བཅུད་བདུད་རྩིའི་ཐིགས་ཕྲེང་། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    1A92:
      image_group_id: I2PD18774
      title: ''
      total_pages: 636
      order: 1
      base_file: 1A92.txt
    ADD6:
      image_group_id: I2PD18775
      title: ''
      total_pages: 286
      order: 2
      base_file: ADD6.txt
    74A7:
      image_group_id: I2PD18776
      title: ''
      total_pages: 338
      order: 3
      base_file: 74A7.txt
    '6078':
      image_group_id: I2PD18777
      title: ''
      total_pages: 266
      order: 4
      base_file: 6078.txt
    C677:
      image_group_id: I2PD18778
      title: ''
      total_pages: 384
      order: 5
      base_file: C677.txt
    0488:
      image_group_id: I2PD18779
      title: ''
      total_pages: 402
      order: 6
      base_file: 0488.txt
    '1648':
      image_group_id: I2PD18780
      title: ''
      total_pages: 316
      order: 7
      base_file: 1648.txt
    D19E:
      image_group_id: I2PD18781
      title: ''
      total_pages: 630
      order: 8
      base_file: D19E.txt
    '4893':
      image_group_id: I2PD18782
      title: ''
      total_pages: 564
      order: 9
      base_file: 4893.txt
    9B14:
      image_group_id: I2PD18783
      title: ''
      total_pages: 476
      order: 10
      base_file: 9B14.txt
    FABF:
      image_group_id: I2PD18784
      title: ''
      total_pages: 852
      order: 11
      base_file: FABF.txt
    31A8:
      image_group_id: I2PD18785
      title: ''
      total_pages: 310
      order: 12
      base_file: 31A8.txt
    D9AF:
      image_group_id: I2PD18786
      title: ''
      total_pages: 288
      order: 13
      base_file: D9AF.txt
    C9EA:
      image_group_id: I2PD18787
      title: ''
      total_pages: 1024
      order: 14
      base_file: C9EA.txt
    59C4:
      image_group_id: I2PD18788
      title: ''
      total_pages: 660
      order: 15
      base_file: 59C4.txt
    A549:
      image_group_id: I2PD18789
      title: ''
      total_pages: 892
      order: 16
      base_file: A549.txt
    68CF:
      image_group_id: I2PD18790
      title: ''
      total_pages: 730
      order: 17
      base_file: 68CF.txt
    0FBD:
      image_group_id: I2PD18791
      title: ''
      total_pages: 588
      order: 18
      base_file: 0FBD.txt
    2E92:
      image_group_id: I2PD18792
      title: ''
      total_pages: 906
      order: 19
      base_file: 2E92.txt
    '3349':
      image_group_id: I2PD18793
      title: ''
      total_pages: 964
      order: 20
      base_file: 3349.txt
    77D5:
      image_group_id: I2PD18794
      title: ''
      total_pages: 586
      order: 21
      base_file: 77D5.txt
    422A:
      image_group_id: I2PD18795
      title: ''
      total_pages: 386
      order: 22
      base_file: 422A.txt
    AC21:
      image_group_id: I2PD18796
      title: ''
      total_pages: 526
      order: 23
      base_file: AC21.txt
    A731:
      image_group_id: I2PD18797
      title: ''
      total_pages: 1022
      order: 24
      base_file: A731.txt
    4E65:
      image_group_id: I2PD18798
      title: ''
      total_pages: 340
      order: 25
      base_file: 4E65.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
