id: P010468
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD152297
  title: 'ཡུལ་མདོ་ཁམས་སྟོད་ཀྱི་མཁས་གྲུབ་རྣམ་པའི་གསུང་བཅུད་བདུད་རྩིའི་ཐིགས་ཕྲེང་། '
  author: ''
  volumes:
    8eaa6e25553648d19f4ef65f7bc0572e:
      image_group_id: I2PD18774
      title: ''
      volume_number: 1
      total_pages: 636
    1ce2fd78992343c0815865de826b7fca:
      image_group_id: I2PD18775
      title: ''
      volume_number: 2
      total_pages: 286
    2ff5ada032c849b996cac8031ca82a5f:
      image_group_id: I2PD18776
      title: ''
      volume_number: 3
      total_pages: 338
    40078a7de0f2458d9022c241400a690a:
      image_group_id: I2PD18777
      title: ''
      volume_number: 4
      total_pages: 266
    71cfd0a3cf98475ca4306add8584fe39:
      image_group_id: I2PD18778
      title: ''
      volume_number: 5
      total_pages: 384
    6c5b73510afa47b1a8cefa0fb4b1352c:
      image_group_id: I2PD18779
      title: ''
      volume_number: 6
      total_pages: 402
    ee0c5068f4e84d2f91834bcb8c3aff7f:
      image_group_id: I2PD18780
      title: ''
      volume_number: 7
      total_pages: 316
    75fa50ad1c114f3ab9f29be7cb43938f:
      image_group_id: I2PD18781
      title: ''
      volume_number: 8
      total_pages: 630
    9d58e9b68e8c49ca947b684f29d6cb5c:
      image_group_id: I2PD18782
      title: ''
      volume_number: 9
      total_pages: 564
    c1bdce0708e54ce48cd4048d1cd1e927:
      image_group_id: I2PD18783
      title: ''
      volume_number: 10
      total_pages: 476
    cf6cc7de05264e668406dd06e88d8629:
      image_group_id: I2PD18784
      title: ''
      volume_number: 11
      total_pages: 852
    bfc2390166b6494b874ce0addf35c7c5:
      image_group_id: I2PD18785
      title: ''
      volume_number: 12
      total_pages: 310
    c4665e04077c43319bfee59ca3f7b3ef:
      image_group_id: I2PD18786
      title: ''
      volume_number: 13
      total_pages: 288
    a9274d7718664827a8538a6412922146:
      image_group_id: I2PD18787
      title: ''
      volume_number: 14
      total_pages: 1024
    9d04e5f5c7354915995a79598565c59c:
      image_group_id: I2PD18788
      title: ''
      volume_number: 15
      total_pages: 660
    9e9cfb4974be42978f9c671b4feac0e8:
      image_group_id: I2PD18789
      title: ''
      volume_number: 16
      total_pages: 892
    f889ace3689944b1b0ebd6da01054d52:
      image_group_id: I2PD18790
      title: ''
      volume_number: 17
      total_pages: 730
    e1615c02294b42d5b9c775efcdee78a6:
      image_group_id: I2PD18791
      title: ''
      volume_number: 18
      total_pages: 588
    2bb1c7abd2b84a27ae54d2ca8e3fb762:
      image_group_id: I2PD18792
      title: ''
      volume_number: 19
      total_pages: 906
    591a8fd2d5304bc784a1ba996d3f740a:
      image_group_id: I2PD18793
      title: ''
      volume_number: 20
      total_pages: 964
    c4b1160296314ffeafb11d20d601adac:
      image_group_id: I2PD18794
      title: ''
      volume_number: 21
      total_pages: 586
    4b5994264cc649deb862604e56f5ea8e:
      image_group_id: I2PD18795
      title: ''
      volume_number: 22
      total_pages: 386
    6e1684f710194b4eaa6b11ede617d925:
      image_group_id: I2PD18796
      title: ''
      volume_number: 23
      total_pages: 526
    9ae63fc34950411f9eb857b3ebb9e36a:
      image_group_id: I2PD18797
      title: ''
      volume_number: 24
      total_pages: 1022
    94b0ddb61165424d94aaa5bcf3cb67f7:
      image_group_id: I2PD18798
      title: ''
      volume_number: 25
      total_pages: 340
